name: Continuous Deployment

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-22.04
    
    steps:
      # SSH를 통한 배포
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          env: |
            DB_URL: ${{ secrets.DB_URL }}
            DB_USERNAME: ${{ secrets.DB_USERNAME }}
            DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
            AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
            AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
            JWT_SECRET: ${{ secrets.JWT_SECRET }}
            ADMIN_SECRET_KEY: ${{ secrets.ADMIN_SECRET_KEY }}
            EDITOR_SECRET_KEY: ${{ secrets.EDITOR_SECRET_KEY }}

          script: |
            echo "DB_URL=$DB_URL"
            echo "DB_USERNAME=$DB_USERNAME"
            echo "DB_PASSWORD=$DB_PASSWORD"
            cd /home/ubuntu/OnlineNews_BE
            git pull origin main
            ./gradlew build -x test
            sudo systemctl stop demo.service
            sudo systemctl restart demo.service
