name: Continuous Deployment

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-22.04
    
    steps:
      # 환경 변수 값 출력(디버깅) 
      - name: Print environment variables
        env:
          DB_URL: ${{ secrets.DB_URL }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          ADMIN_SECRET_KEY: ${{ secrets.ADMIN_SECRET_KEY }}
          EDITOR_SECRET_KEY: ${{ secrets.EDITOR_SECRET_KEY }}
          MAIL_USERNAME : ${{secrets.MAIL_USERNAME}}
          MAIL_PASSWORD : ${{secrets.MAIL_PASSWORD}}

        run: |
          echo "DB_USERNAME=$DB_USERNAME"
          echo "DB_PASSWORD=$DB_PASSWORD"
          echo "DB_URL=$DB_URL"
          echo "AWS_ACCESS_KEY=$AWS_ACCESS_KEY"
          echo "JWT_SECRET=$JWT_SECRET"
          echo "ADMIN_SECRET_KEY=$ADMIN_SECRET_KEY"
          echo "EDITOR_SECRET_KEY=$EDITOR_SECRET_KEY"
          echo "MAIL_USERNAME=$MAIL_USERNAME" 
          echo "MAIL_PASSWORD=$MAIL_PASSWORD" 
          
      # SSH를 통한 배포
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          script: |
            # 환경 변수 직접 삽입 
            DB_URL=${{ secrets.DB_URL }}
            DB_USERNAME=${{ secrets.DB_USERNAME }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }}
            AWS_SECRET_KEY=${{ secrets.AWS_SECRET_KEY }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            ADMIN_SECRET_KEY=${{ secrets.ADMIN_SECRET_KEY }}
            EDITOR_SECRET_KEY=${{ secrets.EDITOR_SECRET_KEY }} 
            MAIL_USERNAME=${{secrets.MAIL_USERNAME}}
            MAIL_PASSWORD=${{secrets.MAIL_PASSWORD}}
            
            # 환경 변수 확인
            echo "DB_URL=$DB_URL"
            echo "DB_USERNAME=$DB_USERNAME"
            echo "DB_PASSWORD=$DB_PASSWORD"
            echo "AWS_ACCESS_KEY=$AWS_ACCESS_KEY"
            echo "JWT_SECRET=$JWT_SECRET"
            echo "ADMIN_SECRET_KEY=$ADMIN_SECRET_KEY"
            echo "EDITOR_SECRET_KEY=$EDITOR_SECRET_KEY"
            echo "MAIL_USERNAME=$MAIL_USERNAME" 
            echo "MAIL_PASSWORD=$MAIL_PASSWORD"
            
            # 배포 스크립트
            cd /home/ubuntu/OnlineNews_BE

            # git 병합 전략 설정 (merge 전략)
            git config pull.rebase false
            git pull origin main
            git status  # 병합 상태 확인

            # 클린 빌드
            chmod +x ./gradlew
            ./gradlew clean build --no-daemon -x test
            chmod +x /home/ubuntu/OnlineNews_BE/build/libs/OnlineNews-0.0.1-SNAPSHOT.jar
            sudo systemctl stop demo.service
            sudo systemctl restart demo.service
